/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ip.project;
import java.sql.*;

import java.util.ArrayList;

/**
 *
 * @author Kshitij
 */
public class BusResult extends javax.swing.JFrame {

    /**
     * Creates new form BusResult
     */
    public BusResult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        h3 = new javax.swing.JCheckBox();
        g2 = new javax.swing.JCheckBox();
        g3 = new javax.swing.JCheckBox();
        g1 = new javax.swing.JCheckBox();
        h2 = new javax.swing.JCheckBox();
        h1 = new javax.swing.JCheckBox();
        e3 = new javax.swing.JCheckBox();
        d2 = new javax.swing.JCheckBox();
        d3 = new javax.swing.JCheckBox();
        d1 = new javax.swing.JCheckBox();
        e2 = new javax.swing.JCheckBox();
        e1 = new javax.swing.JCheckBox();
        f3 = new javax.swing.JCheckBox();
        f1 = new javax.swing.JCheckBox();
        f2 = new javax.swing.JCheckBox();
        b3 = new javax.swing.JCheckBox();
        a2 = new javax.swing.JCheckBox();
        a3 = new javax.swing.JCheckBox();
        a1 = new javax.swing.JCheckBox();
        b2 = new javax.swing.JCheckBox();
        b1 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        c1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        h8 = new javax.swing.JCheckBox();
        g5 = new javax.swing.JCheckBox();
        g6 = new javax.swing.JCheckBox();
        g4 = new javax.swing.JCheckBox();
        h7 = new javax.swing.JCheckBox();
        h6 = new javax.swing.JCheckBox();
        e6 = new javax.swing.JCheckBox();
        d5 = new javax.swing.JCheckBox();
        d6 = new javax.swing.JCheckBox();
        d4 = new javax.swing.JCheckBox();
        e5 = new javax.swing.JCheckBox();
        e4 = new javax.swing.JCheckBox();
        f6 = new javax.swing.JCheckBox();
        f4 = new javax.swing.JCheckBox();
        f5 = new javax.swing.JCheckBox();
        b6 = new javax.swing.JCheckBox();
        a5 = new javax.swing.JCheckBox();
        a6 = new javax.swing.JCheckBox();
        a4 = new javax.swing.JCheckBox();
        b5 = new javax.swing.JCheckBox();
        b4 = new javax.swing.JCheckBox();
        c6 = new javax.swing.JCheckBox();
        c4 = new javax.swing.JCheckBox();
        c5 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        h5 = new javax.swing.JCheckBox();
        h4 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        h3.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        h3.setText("H3");
        h3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                h3ItemStateChanged(evt);
            }
        });

        g2.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        g2.setText("G2");
        g2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                g2ItemStateChanged(evt);
            }
        });

        g3.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        g3.setText("G3");
        g3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                g3ItemStateChanged(evt);
            }
        });

        g1.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        g1.setText("G1");
        g1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                g1ItemStateChanged(evt);
            }
        });

        h2.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        h2.setText("H2");
        h2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                h2ItemStateChanged(evt);
            }
        });

        h1.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        h1.setText("H1");
        h1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                h1ItemStateChanged(evt);
            }
        });

        e3.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        e3.setText("E3");
        e3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                e3ItemStateChanged(evt);
            }
        });

        d2.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        d2.setText("D2");
        d2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                d2ItemStateChanged(evt);
            }
        });

        d3.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        d3.setText("D3");
        d3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                d3ItemStateChanged(evt);
            }
        });

        d1.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        d1.setText("D1");
        d1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                d1ItemStateChanged(evt);
            }
        });

        e2.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        e2.setText("E2");
        e2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                e2ItemStateChanged(evt);
            }
        });

        e1.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        e1.setText("E1");
        e1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                e1ItemStateChanged(evt);
            }
        });

        f3.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        f3.setText("F3");
        f3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                f3ItemStateChanged(evt);
            }
        });

        f1.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        f1.setText("F1");
        f1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                f1ItemStateChanged(evt);
            }
        });

        f2.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        f2.setText("F2");
        f2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                f2ItemStateChanged(evt);
            }
        });

        b3.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        b3.setText("B3");
        b3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                b3ItemStateChanged(evt);
            }
        });

        a2.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        a2.setText("A2");
        a2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                a2ItemStateChanged(evt);
            }
        });

        a3.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        a3.setText("A3");
        a3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                a3ItemStateChanged(evt);
            }
        });

        a1.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        a1.setText("A1");
        a1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                a1ItemStateChanged(evt);
            }
        });

        b2.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        b2.setText("B2");
        b2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                b2ItemStateChanged(evt);
            }
        });

        b1.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        b1.setText("B1");
        b1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                b1ItemStateChanged(evt);
            }
        });

        c3.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        c3.setText("C3");
        c3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c3ItemStateChanged(evt);
            }
        });

        c1.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        c1.setText("C1");
        c1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c1ItemStateChanged(evt);
            }
        });

        c2.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        c2.setText("C2");
        c2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c2ItemStateChanged(evt);
            }
        });

        h8.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        h8.setText("H8");
        h8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                h8ItemStateChanged(evt);
            }
        });

        g5.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        g5.setText("G5");
        g5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                g5ItemStateChanged(evt);
            }
        });

        g6.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        g6.setText("G6");
        g6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                g6ItemStateChanged(evt);
            }
        });

        g4.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        g4.setText("G4");
        g4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                g4ItemStateChanged(evt);
            }
        });

        h7.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        h7.setText("H7");
        h7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                h7ItemStateChanged(evt);
            }
        });

        h6.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        h6.setText("H6");
        h6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                h6ItemStateChanged(evt);
            }
        });

        e6.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        e6.setText("E6");
        e6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                e6ItemStateChanged(evt);
            }
        });

        d5.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        d5.setText("D5");
        d5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                d5ItemStateChanged(evt);
            }
        });

        d6.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        d6.setText("D6");
        d6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                d6ItemStateChanged(evt);
            }
        });

        d4.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        d4.setText("D4");
        d4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                d4ItemStateChanged(evt);
            }
        });

        e5.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        e5.setText("E5");
        e5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                e5ItemStateChanged(evt);
            }
        });

        e4.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        e4.setText("E4");
        e4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                e4ItemStateChanged(evt);
            }
        });

        f6.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        f6.setText("F6");
        f6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                f6ItemStateChanged(evt);
            }
        });

        f4.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        f4.setText("F4");
        f4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                f4ItemStateChanged(evt);
            }
        });

        f5.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        f5.setText("F5");
        f5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                f5ItemStateChanged(evt);
            }
        });

        b6.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        b6.setText("B6");
        b6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                b6ItemStateChanged(evt);
            }
        });

        a5.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        a5.setText("A6");
        a5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                a5ItemStateChanged(evt);
            }
        });

        a6.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        a6.setText("A7");
        a6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                a6ItemStateChanged(evt);
            }
        });

        a4.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        a4.setText("A5");
        a4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                a4ItemStateChanged(evt);
            }
        });

        b5.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        b5.setText("B5");
        b5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                b5ItemStateChanged(evt);
            }
        });

        b4.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        b4.setText("B4");
        b4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                b4ItemStateChanged(evt);
            }
        });

        c6.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        c6.setText("C6");
        c6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c6ItemStateChanged(evt);
            }
        });

        c4.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        c4.setText("C4");
        c4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c4ItemStateChanged(evt);
            }
        });

        c5.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        c5.setText("C5");
        c5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c5ItemStateChanged(evt);
            }
        });

        jLabel1.setText("DRIVERS SEAT");

        jLabel2.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jLabel2.setText("SELECT YOUR SEATS");

        jButton1.setText("Confirm Seats");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        h5.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        h5.setText("H5");
        h5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                h5ItemStateChanged(evt);
            }
        });

        h4.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        h4.setText("H4");
        h4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                h4ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(a4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(a5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(a6, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b5)
                                    .addComponent(b4))
                                .addComponent(b6, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(c6)
                                .addComponent(c5)
                                .addComponent(c4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(d4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(d5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(d6, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(e5)
                                    .addComponent(e4))
                                .addComponent(e6, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(f6)
                                .addComponent(f5)
                                .addComponent(f4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(g4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(g5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(g6, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(h7)
                                    .addComponent(h6))
                                .addComponent(h8, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(a1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(a2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(a3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b2)
                                    .addComponent(b1))
                                .addComponent(b3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(c3)
                                .addComponent(c2)
                                .addComponent(c1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(d1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(d2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(d3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(e2)
                                    .addComponent(e1))
                                .addComponent(e3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(f3)
                                .addComponent(f2)
                                .addComponent(f1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(g1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(g2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(g3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(h2)
                                    .addComponent(h1))
                                .addComponent(h3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(h4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(h5, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addComponent(a3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(h1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(h2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(h3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(g1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(g2)
                            .addGap(25, 25, 25))
                        .addComponent(g3, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(e1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(e2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(e3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(d1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(d2)
                            .addGap(25, 25, 25))
                        .addComponent(d3, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(f1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b1)
                            .addComponent(a1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b2)
                            .addComponent(a2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(c1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(h4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(h5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(h6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(h7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(h8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(e4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(e5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(e6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(d4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(d5)
                            .addGap(25, 25, 25))
                        .addComponent(d6, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(b4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(b5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(b6))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(a4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(a5)
                                .addGap(25, 25, 25))
                            .addComponent(a6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(c4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(c5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(c6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(g4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(g5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(f4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(f5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(g6))))
                .addGap(80, 80, 80)
                .addComponent(jButton1)
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static String BUSId = PlanTravel.BUS_ID;
    public static String date = PlanTravel.bookDate;

public static final int MAX_SEL = PlanTravel.MAX_SEL;
    public int count = 0;
    public ArrayList<String> selSeats = new ArrayList<>();
    public void check(javax.swing.JCheckBox cb){
        if(cb.isSelected()){
            
            selSeats.add(cb.getText());
            count++;
           
            if(count > MAX_SEL){
                cb.setSelected(false);
                selSeats.remove(cb.getText());
            }
        }
        else{
            
            
            selSeats.remove(cb.getText());
            count--;
            
            
        }
    }
    public static void selCheck(javax.swing.JCheckBox cb){
        String s = cb.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/gobus","root","admin12");  
            Statement stmt = con.createStatement();
            String query = "SELECT INSTR(AssignedSeats,'"+s+"') FROM seats WHERE BusID='"+BUSId+"' AND Date='"+ date +"';";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next()){
            int pos = rs.getInt(1);
            if(pos >=1){
                cb.setEnabled(false);
            }
            }
        }
        catch(Exception e){
            System.out.print(e);
            
        }
    }
    public static void setCB(){
        selCheck(a1);
                selCheck(a2);
                selCheck(a3);
                selCheck(a4);
                selCheck(a5);
                selCheck(a6);
                selCheck(b1);
                selCheck(b2);
                selCheck(b3);
                selCheck(b4);
                selCheck(b5);
                selCheck(b6);
                selCheck(c1);
                selCheck(c2);
                selCheck(c3);
                selCheck(c4);
                selCheck(c5);
                selCheck(c6);
                selCheck(d1);
                selCheck(d2);
                selCheck(d3);
                selCheck(d4);
                selCheck(d5);
                selCheck(d6);
                selCheck(e1);
                selCheck(e2);
                selCheck(e3);
                selCheck(e4);
                selCheck(e5);
                selCheck(e6);
                selCheck(f1);
                selCheck(f2);
                selCheck(f3);
                selCheck(f4);
                selCheck(f5);
                selCheck(f6);
                selCheck(g1);
                selCheck(g2);
                selCheck(g3);
                selCheck(g4);
                selCheck(g5);
                selCheck(g6);
                selCheck(h1);
                selCheck(h2);
                selCheck(h3);
                selCheck(h4);
                selCheck(h5);
                selCheck(h6);
                selCheck(h7);
                selCheck(h8);
                
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String s = "";
        for(String x : selSeats){
            s = s + x;
        }
        try{
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/gobus","root","admin12");  
            Statement stmt=con.createStatement();
            String query ;
            ResultSet rs=stmt.executeQuery("select * from seats where BusID ='"+ BUSId + "' AND Date = '" + date +"';");  
            if(rs.next()){  
                String selectedSeats = rs.getString("AssignedSeats");
                query = "UPDATE seats SET AssignedSeats = '"+ selectedSeats+s + "' WHERE BusID ="+ BUSId + " AND Date ='" + date +"';";
                stmt.executeUpdate(query);
            }
            else{
                query = "INSERT INTO seats VALUES('"+BUSId+"','"+date+"', 55-"+MAX_SEL+",'"+s+"');";
                stmt.executeUpdate(query);
            }
                con.close();
              }
        catch(Exception e){
            System.out.print(e);
        }
        new resultpage().setVisible(true);
        this.dispose();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void a1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_a1ItemStateChanged
        // TODO add your handling code here:
        check(a1);

    }//GEN-LAST:event_a1ItemStateChanged

    private void a2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_a2ItemStateChanged
        // TODO add your handling code here:
        check(a2);

    }//GEN-LAST:event_a2ItemStateChanged

    private void a3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_a3ItemStateChanged
        // TODO add your handling code here:
        check(a3);

    }//GEN-LAST:event_a3ItemStateChanged

    private void a4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_a4ItemStateChanged
        // TODO add your handling code here:
        check(a4);

    }//GEN-LAST:event_a4ItemStateChanged

    private void a5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_a5ItemStateChanged
        // TODO add your handling code here:
        check(a5);

    }//GEN-LAST:event_a5ItemStateChanged

    private void a6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_a6ItemStateChanged
        // TODO add your handling code here:
        check(a6);

    }//GEN-LAST:event_a6ItemStateChanged

    private void b2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_b2ItemStateChanged
        // TODO add your handling code here:
        check(b2);

    }//GEN-LAST:event_b2ItemStateChanged

    private void b3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_b3ItemStateChanged
        // TODO add your handling code here:
        check(b3);
    }//GEN-LAST:event_b3ItemStateChanged

    private void b4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_b4ItemStateChanged
        // TODO add your handling code here:
        check(b4);
    }//GEN-LAST:event_b4ItemStateChanged

    private void b1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_b1ItemStateChanged
        // TODO add your handling code here:
        check(b1);
    }//GEN-LAST:event_b1ItemStateChanged

    private void b5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_b5ItemStateChanged
        // TODO add your handling code here:
        check(b5);
    }//GEN-LAST:event_b5ItemStateChanged

    private void b6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_b6ItemStateChanged
        // TODO add your handling code here:
        check(b6);
    }//GEN-LAST:event_b6ItemStateChanged

    private void c1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c1ItemStateChanged
        // TODO add your handling code here:
        check(c1);
    }//GEN-LAST:event_c1ItemStateChanged

    private void c2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c2ItemStateChanged
        // TODO add your handling code here:
        check(c2);
    }//GEN-LAST:event_c2ItemStateChanged

    private void c3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c3ItemStateChanged
        // TODO add your handling code here:
        check(c3);
    }//GEN-LAST:event_c3ItemStateChanged

    private void c4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c4ItemStateChanged
        // TODO add your handling code here:
        check(c4);
    }//GEN-LAST:event_c4ItemStateChanged

    private void c5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c5ItemStateChanged
        // TODO add your handling code here:
        check(c5);
    }//GEN-LAST:event_c5ItemStateChanged

    private void c6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c6ItemStateChanged
        // TODO add your handling code here:
        check(c6);
    }//GEN-LAST:event_c6ItemStateChanged

    private void d1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_d1ItemStateChanged
        // TODO add your handling code here:
        check(d1);
    }//GEN-LAST:event_d1ItemStateChanged

    private void d2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_d2ItemStateChanged
        // TODO add your handling code here:
        check(d2);
    }//GEN-LAST:event_d2ItemStateChanged

    private void d3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_d3ItemStateChanged
        // TODO add your handling code here:
        check(d3);
    }//GEN-LAST:event_d3ItemStateChanged

    private void d4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_d4ItemStateChanged
        // TODO add your handling code here:
        check(d4);
    }//GEN-LAST:event_d4ItemStateChanged

    private void d5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_d5ItemStateChanged
        // TODO add your handling code here:
        check(d5);
    }//GEN-LAST:event_d5ItemStateChanged

    private void d6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_d6ItemStateChanged
        // TODO add your handling code here:
        check(d6);
    }//GEN-LAST:event_d6ItemStateChanged

    private void e1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_e1ItemStateChanged
        // TODO add your handling code here:
        check(e1);
    }//GEN-LAST:event_e1ItemStateChanged

    private void e2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_e2ItemStateChanged
        // TODO add your handling code here:
        check(e2);
    }//GEN-LAST:event_e2ItemStateChanged

    private void e3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_e3ItemStateChanged
        // TODO add your handling code here:
        check(e3);
    }//GEN-LAST:event_e3ItemStateChanged

    private void e4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_e4ItemStateChanged
        // TODO add your handling code here:
        check(e4);
    }//GEN-LAST:event_e4ItemStateChanged

    private void e5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_e5ItemStateChanged
        // TODO add your handling code here:
        check(e5);
    }//GEN-LAST:event_e5ItemStateChanged

    private void e6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_e6ItemStateChanged
        // TODO add your handling code here:
        check(e6);
    }//GEN-LAST:event_e6ItemStateChanged

    private void f1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_f1ItemStateChanged
        // TODO add your handling code here:
        check(f1);
    }//GEN-LAST:event_f1ItemStateChanged

    private void f2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_f2ItemStateChanged
        // TODO add your handling code here:
        check(f2);
    }//GEN-LAST:event_f2ItemStateChanged

    private void f3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_f3ItemStateChanged
        // TODO add your handling code here:
        check(f3);
    }//GEN-LAST:event_f3ItemStateChanged

    private void f4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_f4ItemStateChanged
        // TODO add your handling code here:
        check(f4);
    }//GEN-LAST:event_f4ItemStateChanged

    private void f5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_f5ItemStateChanged
        // TODO add your handling code here:
        check(f5);
    }//GEN-LAST:event_f5ItemStateChanged

    private void f6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_f6ItemStateChanged
        // TODO add your handling code here:
        check(f6);
    }//GEN-LAST:event_f6ItemStateChanged

    private void g1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_g1ItemStateChanged
        // TODO add your handling code here:
        check(g1);
    }//GEN-LAST:event_g1ItemStateChanged

    private void g2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_g2ItemStateChanged
        // TODO add your handling code here:
        check(g2);
    }//GEN-LAST:event_g2ItemStateChanged

    private void g3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_g3ItemStateChanged
        // TODO add your handling code here:
        check(g3);
    }//GEN-LAST:event_g3ItemStateChanged

    private void g4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_g4ItemStateChanged
        // TODO add your handling code here:
        check(g4);
    }//GEN-LAST:event_g4ItemStateChanged

    private void g5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_g5ItemStateChanged
        // TODO add your handling code here:
        check(g5);
    }//GEN-LAST:event_g5ItemStateChanged

    private void g6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_g6ItemStateChanged
        // TODO add your handling code here:
        check(g6);
    }//GEN-LAST:event_g6ItemStateChanged

    private void h1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_h1ItemStateChanged
        // TODO add your handling code here:
        check(h1);
    }//GEN-LAST:event_h1ItemStateChanged

    private void h2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_h2ItemStateChanged
        // TODO add your handling code here:
        check(h2);
    }//GEN-LAST:event_h2ItemStateChanged

    private void h3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_h3ItemStateChanged
        // TODO add your handling code here:
        check(h3);
    }//GEN-LAST:event_h3ItemStateChanged

    private void h4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_h4ItemStateChanged
        // TODO add your handling code here:
        check(h4);
    }//GEN-LAST:event_h4ItemStateChanged

    private void h5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_h5ItemStateChanged
        // TODO add your handling code here:
        check(h5);
    }//GEN-LAST:event_h5ItemStateChanged

    private void h6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_h6ItemStateChanged
        // TODO add your handling code here:
        check(h6);
    }//GEN-LAST:event_h6ItemStateChanged

    private void h7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_h7ItemStateChanged
        // TODO add your handling code here:
        check(h7);
    }//GEN-LAST:event_h7ItemStateChanged

    private void h8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_h8ItemStateChanged
        // TODO add your handling code here:
        check(h8);
    }//GEN-LAST:event_h8ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusResult().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JCheckBox a1;
    private static javax.swing.JCheckBox a2;
    private static javax.swing.JCheckBox a3;
    private static javax.swing.JCheckBox a4;
    private static javax.swing.JCheckBox a5;
    private static javax.swing.JCheckBox a6;
    private static javax.swing.JCheckBox b1;
    private static javax.swing.JCheckBox b2;
    private static javax.swing.JCheckBox b3;
    private static javax.swing.JCheckBox b4;
    private static javax.swing.JCheckBox b5;
    private static javax.swing.JCheckBox b6;
    private static javax.swing.JCheckBox c1;
    private static javax.swing.JCheckBox c2;
    private static javax.swing.JCheckBox c3;
    private static javax.swing.JCheckBox c4;
    private static javax.swing.JCheckBox c5;
    private static javax.swing.JCheckBox c6;
    private static javax.swing.JCheckBox d1;
    private static javax.swing.JCheckBox d2;
    private static javax.swing.JCheckBox d3;
    private static javax.swing.JCheckBox d4;
    private static javax.swing.JCheckBox d5;
    private static javax.swing.JCheckBox d6;
    private static javax.swing.JCheckBox e1;
    private static javax.swing.JCheckBox e2;
    private static javax.swing.JCheckBox e3;
    private static javax.swing.JCheckBox e4;
    private static javax.swing.JCheckBox e5;
    private static javax.swing.JCheckBox e6;
    private static javax.swing.JCheckBox f1;
    private static javax.swing.JCheckBox f2;
    private static javax.swing.JCheckBox f3;
    private static javax.swing.JCheckBox f4;
    private static javax.swing.JCheckBox f5;
    private static javax.swing.JCheckBox f6;
    private static javax.swing.JCheckBox g1;
    private static javax.swing.JCheckBox g2;
    private static javax.swing.JCheckBox g3;
    private static javax.swing.JCheckBox g4;
    private static javax.swing.JCheckBox g5;
    private static javax.swing.JCheckBox g6;
    private static javax.swing.JCheckBox h1;
    private static javax.swing.JCheckBox h2;
    private static javax.swing.JCheckBox h3;
    private static javax.swing.JCheckBox h4;
    private static javax.swing.JCheckBox h5;
    private static javax.swing.JCheckBox h6;
    private static javax.swing.JCheckBox h7;
    private static javax.swing.JCheckBox h8;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
